# Generated by Django 5.2 on 2026-03-28 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "loans",
            "0004_rename_loans_loan_reader_status_idx_loans_loan_reader__44aff0_idx_and_more",
        ),
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "type"], name="notificatio_user_id_827754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["sent_at"], name="notificatio_sent_at_265656_idx"
            ),
        ),
    ]
