# Generated by Django 5.2 on 2026-03-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_gender_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_account_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_overdue",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_reminders",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_reservation",
            field=models.BooleanField(default=True),
        ),
    ]
