# Generated by Django 5.2 on 2026-03-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("overdue", "Overdue"),
                            ("damage", "Damage"),
                            ("loss", "Loss"),
                        ],
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "penalties",
                "ordering": ["-loan__borrowed_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["-reserved_at"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowed_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("prolongation_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("overdue", "Overdue"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="catalog.bookcopy",
                    ),
                ),
            ],
            options={
                "ordering": ["-borrowed_at"],
            },
        ),
    ]
