# Generated by Django 5.2 on 2026-03-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_loans_updates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loan",
            new_name="loans_loan_reader__44aff0_idx",
            old_name="loans_loan_reader_status_idx",
        ),
        migrations.RenameIndex(
            model_name="loan",
            new_name="loans_loan_copy_id_dd4cfb_idx",
            old_name="loans_loan_copy_status_idx",
        ),
    ]
