# Generated by Django 5.2 on 2026-03-28 18:40

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ol_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("isbn", models.CharField(blank=True, max_length=20, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("cover_url", models.URLField(blank=True)),
                (
                    "genres",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("copy_number", models.PositiveIntegerField()),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("good", "Good"), ("worn", "Worn")],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes/")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "ordering": ["book", "copy_number"],
                "unique_together": {("book", "copy_number")},
            },
        ),
    ]
