# Generated by Django 5.2 on 2026-03-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_catalog_updates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="book",
            new_name="catalog_boo_search__d12de2_gin",
            old_name="catalog_book_search_vector_gin",
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="ol_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunSQL(
            sql="UPDATE catalog_book SET ol_id = NULL WHERE ol_id = '';",
            reverse_sql="UPDATE catalog_book SET ol_id = '' WHERE ol_id IS NULL;",
        ),
        migrations.RunSQL(
            sql="UPDATE catalog_book SET isbn = NULL WHERE isbn = '';",
            reverse_sql="UPDATE catalog_book SET isbn = '' WHERE isbn IS NULL;",
        ),
    ]
